### ISSUE TITLE
More functionality

### ISSUE THREAD

**Issue by Eleventh-11th** [Dhiraj072/random-word-generator#1]
Hey, first of all, this is not an issue. I came across your article on dev.io and tried out your API for a hangman game that I am building for fun. It is great, but I wonder whether there're more commands than ```RandomWordGenerator.getRandomWord()``` to use. For example, it would be lovely to add a perimeter where I can choose my own topic.
Thanks.

**Comment by Dhiraj072** [comment]
Hey @justdont, sorry for the late response. I haven't been actively monitoring this. I think what you're asking is a nice feature to have. Feel free to contribute if you'd like! I will try and add this feature as I get time!
